In [ ]:
# Samarth Deshmukh
# 25070123101
# exp 12 : Categorial data analysis using python

In [1]:
import pandas as pd

df = pd.read_csv("/content/Expt11.csv")

display(df)

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [2]:
#12.1.1 Number of Students in each Department, Each Gender and Each Grade


print(df['Grade'].value_counts())

print(df['Gender'].value_counts())

print(df['Department'].value_counts())

Grade
B    24
A    22
C    14
Name: count, dtype: int64
Gender
Male      30
Female    30
Name: count, dtype: int64
Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [3]:
#12.1.2 Percentage distribution of Grades

display("Grade Percentage")
display(df['Grade'].value_counts(normalize=True)*100)

'Grade Percentage'

Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [4]:
#12.1.3 Gender vs Grade Analysis, Department vs Gender Analysis, Department vs Grade Analysis

display(pd.crosstab(df['Gender'],df['Grade']))

display(pd.crosstab(df['Department'],df['Gender']))

display(pd.crosstab(df['Department'],df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

Grade        A  B  C
Department
CSE         13  4  3
ECE          2  5  4
IT           7  8  3
Mechanical   0  7  4

In [5]:
#12.1.4 Department vs Grade Percentage Analysis

display(pd.crosstab(df['Department'], df['Grade'], normalize='index')*100)

Grade               A          B          C
Department
CSE         65.000000  20.000000  15.000000
ECE         18.181818  45.454545  36.363636
IT          38.888889  44.444444  16.666667
Mechanical   0.000000  63.636364  36.363636

In [6]:
#12.1.5 Grouping Data

display(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64

In [7]:
import pandas as pd

data = {
'Order_ID':['01','02','03','04','05','06','07','08','09','10'],

'Category':['Electronics','Clothing','Electronics','Grocery','Clothing',
            'Electronics','Grocery','Clothing','Electronics','Grocery'],

'Payment_Method':['UPI','Card','UPI','Cash','Card',
                  'UPI','Cash','Card','UPI','Cash'],

'Delivery_Type':['Express','Standard','Express','Standard','Express',
                 'Standard','Express','Standard','Express','Standard'],

'Customer_Type':['New','Returning','Returning','New','Returning',
                 'New','Returning','New','Returning','New']
}

df = pd.DataFrame(data)

display(df)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       01  Electronics            UPI       Express           New
1       02     Clothing           Card      Standard     Returning
2       03  Electronics            UPI       Express     Returning
3       04      Grocery           Cash      Standard           New
4       05     Clothing           Card       Express     Returning
5       06  Electronics            UPI      Standard           New
6       07      Grocery           Cash       Express     Returning
7       08     Clothing           Card      Standard           New
8       09  Electronics            UPI       Express     Returning
9       10      Grocery           Cash      Standard           New

In [8]:
#12.2.1 Frequency Count

display(df['Category'].value_counts())

Category
Electronics    4
Clothing       3
Grocery        3
Name: count, dtype: int64

In [9]:
#12.2.2 Percentage Distribution

display(df['Category'].value_counts(normalize=True)*100)

Category
Electronics    40.0
Clothing       30.0
Grocery        30.0
Name: proportion, dtype: float64

In [10]:
#12.2.3 Payment Method Analysis

display(df['Payment_Method'].value_counts())

Payment_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

In [11]:
#12.2.4 Unique Values

print(df['Category'].unique())

['Electronics' 'Clothing' 'Grocery']

In [12]:
#12.2.5 no. of unique Values

print(df['Category'].nunique())

3

In [13]:
#12.2.6 Filtering Data

electronics_orders = df[df['Category']=='Electronics']

display(electronics_orders)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       01  Electronics            UPI       Express           New
2       03  Electronics            UPI       Express     Returning
5       06  Electronics            UPI      Standard           New
8       09  Electronics            UPI       Express     Returning

In [14]:
#12.2.7 Sorting Data

sorted_df = df.sort_values(by='Category')
display(sorted_df)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
1       02     Clothing           Card      Standard     Returning
4       05     Clothing           Card       Express     Returning
7       08     Clothing           Card      Standard           New
0       01  Electronics            UPI       Express           New
2       03  Electronics            UPI       Express     Returning
5       06  Electronics            UPI      Standard           New
8       09  Electronics            UPI       Express     Returning
3       04      Grocery           Cash      Standard           New
6       07      Grocery           Cash       Express     Returning
9       10      Grocery           Cash      Standard           New

In [15]:
#12.2.8 Grouping

display(df.groupby('Category')['Payment_Method'].value_counts())

Category     Payment_Method
Clothing     Card              3
Electronics  UPI               4
Grocery      Cash              3
Name: count, dtype: int64